DROP TABLE TBL_SHJ_STAFF ;
DROP TABLE  TBL_SHJ_DEPARTMENT ;
DROP TABLE  TBL_SHJ_COMPANY ;

CREATE TABLE `TBL_SHJ_COMPANY` 
(	`ID` VARCHAR(32) NOT NULL, 
	`ADDRESS` VARCHAR(255), 
	`CREATED_BY` VARCHAR(50), 
	`CREATED_DT` DATE, 
	`ESTABLISH_DATE` DATE, 
	`COM_NAME` VARCHAR(100) NOT NULL, 
	`POSTCODE` VARCHAR(6), 
	`UPDATED_BY` VARCHAR(50), 
	`UPDATED_DT` DATE, 
	`VERSION` INT NOT NULL, 
	`BOSS_ID` VARCHAR(32), 
	 PRIMARY KEY (`ID`)
);
   
CREATE TABLE `TBL_SHJ_DEPARTMENT` 
(	`ID` VARCHAR(32) NOT NULL , 
	`CREATED_BY` VARCHAR(50), 
	`CREATED_DT` DATE, 
	`DOMAIN` VARCHAR(255), 
	`DEP_NAME` VARCHAR(100), 
	`UPDATED_BY` VARCHAR(50), 
	`UPDATED_DT` DATE, 
	`VERSION` INT NOT NULL , 
	`COMPANY_ID` VARCHAR(32) NOT NULL , 
	`PM_ID` VARCHAR(32), 
	 PRIMARY KEY (`ID`),
	 CONSTRAINT `FK_COMPANY_ID` FOREIGN KEY (`COMPANY_ID`)
	  REFERENCES `TBL_SHJ_COMPANY` (`ID`) 
) ;


CREATE TABLE `TBL_SHJ_STAFF` 
(	`ID` VARCHAR(32) NOT NULL , 
	`AGE` INT, 
	`CREATED_BY` VARCHAR(50), 
	`CREATED_DT` DATE, 
	`NAME` VARCHAR(100), 
	`UPDATED_BY` VARCHAR(50), 
	`UPDATED_DT` DATE, 
	`VERSION` INT NOT NULL , 
	`DEP_ID` VARCHAR(32) NOT NULL , 
	 PRIMARY KEY (`ID`), 
	 CONSTRAINT `FK_DEP_ID` FOREIGN KEY (`DEP_ID`)
	  REFERENCES `TBL_SHJ_DEPARTMENT` (`ID`)
);

ALTER TABLE `TBL_SHJ_DEPARTMENT` ADD CONSTRAINT `FK_PM_ID` FOREIGN KEY (`PM_ID`)
	  REFERENCES `TBL_SHJ_STAFF` (`ID`) ;

ALTER TABLE `TBL_SHJ_COMPANY` ADD CONSTRAINT `FK_BOSS_ID` FOREIGN KEY (`BOSS_ID`)
	 REFERENCES `TBL_SHJ_STAFF` (`ID`);
 